src/Entity/Sortie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * Sortie
 *@ORM\Entity(repositoryClass="App\Repository\SortiesRepository")
 * @ORM\Table(name="sorties")
 * @ORM\Entity
 */
class Sortie
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $Id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255, nullable=false)
     */
    private $nom;

    /**
     * @var \DateTime
     *
     * @Assert\GreaterThan("today",message="La date saisie doit etre supérieur à celle du jour")
     *
     * @ORM\Column(name="datedebut", type="datetime", nullable=false)
     */
    private $datedebut;

    /**
     * @var int|null
     * @Assert\GreaterThan(30,message="La durée doit etre au minimum de 30  min")
     * @ORM\Column(name="duree", type="integer", nullable=true)
     */
    private $duree;

    /**
     * @var \DateTime
     *@Assert\GreaterThan("today")
     *@Assert\LessThan(propertyPath="datedebut")
     *
     * @ORM\Column(name="datecloture", type="datetime", nullable=false)
     */
    private $datecloture;

    /**
     * @var int
     *@Assert\GreaterThan(0)
     * @ORM\Column(name="nbinscriptionsmax", type="integer", nullable=false)
     */
    private $nbinscriptionsmax;

    /**
     * @var string|null
     *@Assert\NotBlank()
     * @ORM\Column(name="descriptioninfos", type="string", length=500, nullable=true)
     */
    private $descriptioninfos;



    /**
     * @var string|null
     *
     * @ORM\Column(name="urlPhoto", type="string", length=250, nullable=true)
     */
    private $urlphoto;



    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Inscription", mappedBy="sortie", orphanRemoval=true,cascade={"persist"})
     */
    private $inscriptions;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Etat", inversedBy="sorties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Lieu", inversedBy="sorties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Lieu;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Participant", inversedBy="sorties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $organisateur;

    public function __construct()
    {
        $this->inscriptions = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->Id;
    }

    /**
     * @param int $Id
     */
    public function setId(int $Id)
    {
        $this->Id = $Id;
    }

    /**
     * @return string
     */
    public function getNom(): ?string
    {
        return $this->nom;
    }

    /**
     * @param string $nom
     */
    public function setNom(string $nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return \DateTime
     */
    public function getDatedebut(): ?\DateTime
    {
        return $this->datedebut;
    }

    /**
     * @param \DateTime $datedebut
     */
    public function setDatedebut(\DateTime $datedebut)
    {
        $this->datedebut = $datedebut;
    }

    /**
     * @return int|null
     */
    public function getDuree(): ?int
    {
        return $this->duree;
    }

    /**
     * @param int|null $duree
     */
    public function setDuree(int $duree)
    {
        $this->duree = $duree;
    }

    /**
     * @return \DateTime
     */
    public function getDatecloture(): ?\DateTime
    {
        return $this->datecloture;
    }

    /**
     * @param \DateTime $datecloture
     */
    public function setDatecloture(\DateTime $datecloture)
    {
        $this->datecloture = $datecloture;
    }

    /**
     * @return int
     */
    public function getNbinscriptionsmax(): ?int
    {
        return $this->nbinscriptionsmax;
    }

    /**
     * @param int $nbinscriptionsmax
     */
    public function setNbinscriptionsmax(int $nbinscriptionsmax)
    {
        $this->nbinscriptionsmax = $nbinscriptionsmax;
    }

    /**
     * @return string|null
     */
    public function getDescriptioninfos(): ?string
    {
        return $this->descriptioninfos;
    }

    /**
     * @param string|null $descriptioninfos
     */
    public function setDescriptioninfos(string $descriptioninfos)
    {
        $this->descriptioninfos = $descriptioninfos;
    }

    
    /**
     * @return string|null
     */
    public function getUrlphoto(): ?string
    {
        return $this->urlphoto;
    }

    /**
     * @param string|null $urlphoto
     */
    public function setUrlphoto(string $urlphoto)
    {
        $this->urlphoto = $urlphoto;
    }


    /**
     * @return Collection|Inscription[]
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscription $inscription): self
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions[] = $inscription;
            $inscription->setSortie($this);
        }

        return $this;
    }

    public function removeInscription(Inscription $inscription): self
    {
        if ($this->inscriptions->contains($inscription)) {
            $this->inscriptions->removeElement($inscription);
            // set the owning side to null (unless already changed)
            if ($inscription->getSortie() === $this) {
                $inscription->setSortie(null);
            }
        }

        return $this;
    }

    public function getEtat(): ?Etat
    {
        return $this->etat;
    }

    public function setEtat(?Etat $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getLieu(): ?Lieu
    {
        return $this->Lieu;
    }

    public function setLieu(?Lieu $Lieu): self
    {
        $this->Lieu = $Lieu;

        return $this;
    }

    public function getOrganisateur(): ?Participant
    {
        return $this->organisateur;
    }

    public function setOrganisateur(?Participant $organisateur): self
    {
        $this->organisateur = $organisateur;

        return $this;
    }
}

src/Entity/Sorties.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Sorties
 *
 * @ORM\Table(name="sorties", indexes={@ORM\Index(name="organisateur", columns={"organisateur"}), @ORM\Index(name="etats_no_etat", columns={"etats_no_etat"})})
 * @ORM\Entity
 */
class Sorties
{
    /**
     * @var int
     *
     * @ORM\Column(name="no_sortie", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $noSortie;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=30, nullable=false)
     */
    private $nom;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datedebut", type="date", nullable=false)
     */
    private $datedebut;

    /**
     * @var int|null
     *
     * @ORM\Column(name="duree", type="integer", nullable=true)
     */
    private $duree;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datecloture", type="date", nullable=false)
     */
    private $datecloture;

    /**
     * @var int
     *
     * @ORM\Column(name="nbinscriptionsmax", type="integer", nullable=false)
     */
    private $nbinscriptionsmax;

    /**
     * @var string|null
     *
     * @ORM\Column(name="descriptioninfos", type="string", length=500, nullable=true)
     */
    private $descriptioninfos;

    /**
     * @var int|null
     *
     * @ORM\Column(name="etatsortie", type="integer", nullable=true)
     */
    private $etatsortie;

    /**
     * @var string|null
     *
     * @ORM\Column(name="urlPhoto", type="string", length=250, nullable=true)
     */
    private $urlphoto;

    /**
     * @var int
     *
     * @ORM\Column(name="organisateur", type="integer", nullable=false)
     */
    private $organisateur;

    /**
     * @var int
     *
     * @ORM\Column(name="lieux_no_lieu", type="integer", nullable=false)
     */
    private $lieuxNoLieu;

    /**
     * @var int
     *
     * @ORM\Column(name="etats_no_etat", type="integer", nullable=false)
     */
    private $etatsNoEtat;

    /**
     * @return int
     */
    public function getNoSortie(): int
    {
        return $this->noSortie;
    }

    /**
     * @param int $noSortie
     */
    public function setNoSortie(int $noSortie)
    {
        $this->noSortie = $noSortie;
    }

    /**
     * @return string
     */
    public function getNom(): string
    {
        return $this->nom;
    }

    /**
     * @param string $nom
     */
    public function setNom(string $nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return \DateTime
     */
    public function getDatedebut(): \DateTime
    {
        return $this->datedebut;
    }

    /**
     * @param \DateTime $datedebut
     */
    public function setDatedebut(\DateTime $datedebut)
    {
        $this->datedebut = $datedebut;
    }

    /**
     * @return int|null
     */
    public function getDuree(): int
    {
        return $this->duree;
    }

    /**
     * @param int|null $duree
     */
    public function setDuree(int $duree)
    {
        $this->duree = $duree;
    }

    /**
     * @return \DateTime
     */
    public function getDatecloture(): \DateTime
    {
        return $this->datecloture;
    }

    /**
     * @param \DateTime $datecloture
     */
    public function setDatecloture(\DateTime $datecloture)
    {
        $this->datecloture = $datecloture;
    }

    /**
     * @return int
     */
    public function getNbinscriptionsmax(): int
    {
        return $this->nbinscriptionsmax;
    }

    /**
     * @param int $nbinscriptionsmax
     */
    public function setNbinscriptionsmax(int $nbinscriptionsmax)
    {
        $this->nbinscriptionsmax = $nbinscriptionsmax;
    }

    /**
     * @return string|null
     */
    public function getDescriptioninfos(): string
    {
        return $this->descriptioninfos;
    }

    /**
     * @param string|null $descriptioninfos
     */
    public function setDescriptioninfos(string $descriptioninfos)
    {
        $this->descriptioninfos = $descriptioninfos;
    }

    /**
     * @return int|null
     */
    public function getEtatsortie(): int
    {
        return $this->etatsortie;
    }

    /**
     * @param int|null $etatsortie
     */
    public function setEtatsortie(int $etatsortie)
    {
        $this->etatsortie = $etatsortie;
    }

    /**
     * @return string|null
     */
    public function getUrlphoto(): string
    {
        return $this->urlphoto;
    }

    /**
     * @param string|null $urlphoto
     */
    public function setUrlphoto(string $urlphoto)
    {
        $this->urlphoto = $urlphoto;
    }

    /**
     * @return int
     */
    public function getOrganisateur(): int
    {
        return $this->organisateur;
    }

    /**
     * @param int $organisateur
     */
    public function setOrganisateur(int $organisateur)
    {
        $this->organisateur = $organisateur;
    }

    /**
     * @return int
     */
    public function getLieuxNoLieu(): int
    {
        return $this->lieuxNoLieu;
    }

    /**
     * @param int $lieuxNoLieu
     */
    public function setLieuxNoLieu(int $lieuxNoLieu)
    {
        $this->lieuxNoLieu = $lieuxNoLieu;
    }

    /**
     * @return int
     */
    public function getEtatsNoEtat(): int
    {
        return $this->etatsNoEtat;
    }

    /**
     * @param int $etatsNoEtat
     */
    public function setEtatsNoEtat(int $etatsNoEtat)
    {
        $this->etatsNoEtat = $etatsNoEtat;
    }
}

src/Controller/SortieController.php
<?php

namespace App\Controller;

use App\Entity\Sortie;
use App\Form\CreateSortieType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class SortieController extends Controller
{
    /**
     * @Route(
     * "/create_sortie",
     * name="index_sortie",
     * methods={"GET"}
     * )
     * @param EntityManagerInterface $em
     * @param Request $request
     * @return Response
     */
    public function index(EntityManagerInterface $em,
                             Request $request)
    {

        $sortie = new Sortie();
        $sortieForm = $this->createForm(CreateSortieType::class, $sortie);

        $sortieForm->handleRequest($request);
        if ($sortieForm->isSubmitted() && $sortieForm->isValid()) {



           // $em->flush();
            return $this->redirectToRoute("participant_login");
//            $token = new UsernamePasswordToken($user, null,
//                'main', $user->getRoles());
//            $this->container->get('security.token_storage')->setToken($token);
//            $this->container->get('session')->set('_security_main', serialize($token));
//            return $this->redirectToRoute('article_liste');
        }

        return $this->render('sortie/create.html.twig', ["form" => $sortieForm->createView()]);
    }


    /**
     * @Route(
     * "/create_sortie",
     * name="create_sortie",
     * methods={"POST"}
     * )
     * @param EntityManagerInterface $em
     * @param Request $request
     * @return Response
     */
    public function post(EntityManagerInterface $em,
                          Request $request)
    {
        $sortie = new Sortie();
        $sortieForm = $this->createForm(CreateSortieType::class, $sortie);
        $sortieForm->submit();
        $sortieForm->handleRequest($request);
        return $this->render('sortie/create.html.twig', ["form" => $sortieForm]);
    }
}

templates/sortie/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer une Sortie | {{ parent() }}{% endblock %}

{% block main %}
	<div class="my-custom-class-for-errors">
		{{ form_errors(form) }}
	</div>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12 title-div">
				<h1>
					NOUVELLE SORTIE
				</h1>
			</div>
		</div>

		{{ form_start(form,  { 'attr':{'class': 'row css-selector-to-form'}}) }}
		<div class="col-md-6">
			<div class="form-group">
				{{ form_row(form.nom) }}
			</div>
			<div class="form-group">
				{{ form_row(form.datedebut) }}
			</div>
			<div class="form-group">
				{{ form_row(form.datecloture) }}
			</div>
			<div class="form-group">
				{{ form_row(form.nbinscriptionsmax) }}
			</div>
			<div class="form-group">
				{{ form_row(form.duree) }}
			</div>
			<div class="form-group">
				{% autoescape false %}
				{{ form_row(form.descriptioninfos) }}
				{% endautoescape %}
			</div>
		</div>
		<div class="col-md-6">
			<div class="form-group">
				<label for="vileOrganisatrice">Ville organisatrice</label>
				<input class="form-control" type="text" placeholder="{{  organisateur.nomSite| upper }}" readonly name="vileOrganisatrice">
			</div>
			<div class="form-group">
				{{ form_row(form.ville,{ 'attr':{'data-api': path('api_lieu')}}) }}
			</div>
				<div class="form-group">
					{{ form_row(form.lieu) }}

						<button id="btn-pop-lieu" class="btn-common btn-add-lieu" data-toggle="modal" data-target="#modal-lieu">
							<i class="fas fa-plus-square"></i>
						</button>
					{% include 'lieu/lieu_modal.html.twig' %}

				</div>
			<div class="form-group" >
				<label for="create_sortie[rue]">Rue</label>
				<span class="form-control bg-light"  id="create_sortie_rue"></span>
			</div>
			<div class="form-group">
				<label for="create_sortie[codePostal]">Code Postal</label>
				<span class="form-control bg-light"  id="create_sortie_cp"></span>
			</div>
			<div class="form-group">
				<label for="create_sortie[longitude]">longitude</label>
				<span class="form-control bg-light"  id="create_sortie_lon"></span>
			</div>
			<div class="form-group">
				<label for="create_sortie[latitude]">latitude</label>
				<span class="form-control bg-light"  id="create_sortie_lat"></span>
			</div>





			<div class="form-group">
				{{ form_row(form.duree) }}
			</div>
			<div class="form-group">
				{{ form_row(form.descriptioninfos) }}
			</div>
		</div>


	<div class="mx-auto">

		<div class="row">
			<div class="col-md-4">
					{{ form_row(form.save) }}
			</div>
			<div class="col-md-4">

					{{ form_row(form.publish) }}

			</div>
			<div class="col-md-4">

				<button type="button" class="btn  btn-block bg-danger"  onclick="location.href='{{path('sorties')}}'">
					Annuler
				</button>
			</div>

		</div>


	</div>


	</div>
	{{ form_end(form) }}

{% endblock %}

templates/sortie/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail  d'une Sortie | {{ parent() }}{% endblock %}

{% block main %}
<div class="container-fluid" xmlns="http://www.w3.org/1999/html">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">
                {{sortie.nom}}
            </h1>
        </div>
    </div>
    <div >
        <label><b>Nom de la sortie:</b> {{ sortie.nom}}</label>
    </div>
   <div>
       <label><b>Date et heure de début :</b>{{ sortie.datedebut | date('d/m/Y H:i')}} </label>
   </div>
    <diV>
        <label><b>Date limite d'inscription:</b>{{ sortie.datecloture | date('d/m/Y H:i') }}</label>
    </diV>
    <div>
        <label><b>Nombre de places:</b> {{ sortie.nbinscriptionsmax }}</label>
    </div>

    <div>
        <label><b>Etat:</b> {{ sortie.etat.libelle }}</label>
    </div>

    <div>
        <label><b>Description et info:</b> {{ sortie.descriptioninfos }}</label>
    </div>

    <div> <label><b> Ville Organisatrice:</b> <span class="uppecase"> {{ sortie.organisateur.site.nomSite }} </span></label>
    </div>
    <div>
        <label><b>Lieu:</b> {{ sortie.lieu.nomLieu }}</label>
    </div>
    <div>
        <label><b>Rue:</b> {{ sortie.lieu.rue }}</label>
    </div>
    <div>
        <label><b>Code Postal :</b> {{ sortie.lieu.ville.codePostal }}</label>
    </div>

    <div>
        <label><b>Longitude:</b> {{ sortie.lieu.longitude }}</label>
    </div>

    <div>
        <label><b>Latitude:</b> {{ sortie.lieu.latitude }}</label>

    </div>

    <div>
        <label><b>Participants:</b><br>
            {% for inscription in sortie.inscriptions %}
                {{ inscription.participant.nom }} <br>
            {% endfor %}
        </label>

    </div>


</div>
{% endblock %}

templates/sortie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer une Sortie | {{ parent() }}{% endblock %}

{% block main %}
    <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-center">
                    Editer une sortie
                </h3>
            </div>
        </div>

        {{ form_start(form,  { 'attr': {'class': 'row'} }) }}

        <div class="col-md-6">
            <div class="form-group">
                {{ form_row(form.nom) }}
            </div>
            <div class="form-group">
                {{ form_row(form.datedebut) }}
            </div>
            <div class="form-group">
                {{ form_row(form.datecloture) }}
            </div>
            <div class="form-group">
                {{ form_row(form.nbinscriptionsmax) }}
            </div>
            <div class="form-group">
                {{ form_row(form.duree) }}
            </div>
            <div class="form-group">
                {% autoescape false %}
                    {{ form_row(form.descriptioninfos) }}
                {% endautoescape %}
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="vileOrganisatrice">Ville organisatrice</label>
                <input class="form-control uppecase" type="text" placeholder="{{sortie.organisateur.site.nomSite}}" readonly name="vileOrganisatrice">
            </div>
            <div class="form-group">
                {{ form_row(form.ville,{ 'attr':{'data-api': path('api_lieu')}}) }}
            </div>
            <div class="form-group">
                {{ form_row(form.lieu) }}

                    <button id="btn-pop-lieu" class="btn-common btn-add-lieu" data-toggle="modal" data-target="#modal-lieu">
                        <i class="fas fa-plus-square"></i>
                    </button>
                    {% include 'lieu/lieu_modal.html.twig' %}

            </div>
            <div class="form-group">
                {{ form_row(form.lieu) }}
            </div>

            <div class="form-group" >
                <label for="create_sortie[rue]">Rue</label>
                <span class="form-control bg-light"  id="create_sortie_rue">{{ sortie.lieu.rue}}</span>
            </div>
            <div class="form-group">
                <label for="create_sortie[codePostal]">Code Postal</label>
                <span class="form-control bg-light"  id="create_sortie_cp">{{ sortie.lieu.ville.codePostal}}</span>
            </div>
            <div class="form-group">
                <label for="create_sortie[longitude]">longitude</label>
                <span class="form-control bg-light"  id="create_sortie_lon">{{ sortie.lieu.longitude}}</span>
            </div>
            <div class="form-group">
                <label for="create_sortie[latitude]">latitude</label>
                <span class="form-control bg-light"  id="create_sortie_lat">{{ sortie.lieu.latitude}}</span>
            </div>






        </div>


        <div class="mx-auto">

            <div class="row">
                <div class="col-md-4">
                    {{ form_row(form.save) }}
                </div>
                <div class="col-md-4">

                    {{ form_row(form.publish) }}

                </div>
                {{ form_end(form) }}

                <div class="col-md-4">

                    <button type="button" class="btn  btn-danger"  onclick="location.href='{{path('sorties')}}'">
                        Annuler
                    </button>
                </div>


                <div class="row">
                    <form method="post"
                          action="{{ path("sortie_delete", {'id' : sortie.id }) }}"
                          onsubmit="return confirm('Confirmation de la suppression ?');">
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete'~sortie.id) }}">
                        <button class="btn btn-danger">Supprimer</button>
                    </form>
                </div>

            </div>


        </div>


    </div>



{% endblock %}

templates/sortie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil - Les sorties {% endblock %}

{% block main %}
    <div id="index-sorties" class="container-fluid">
        <div class="row">
            <div class="col-md-12 title-div">
                <h1> VOS SORTIES </h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h2>Bienvenue {{ app.user.prenom ~ " " ~ app.user.nom| slice(0, 1) |upper ~ '.'  }} ! </h2>
                <h3>nous sommes le {{ "now"|date("m/d/Y") }}</h3>
            </div>
        </div>
        <div>
            {{ form_start(form) }}
            <div class="my-custom-class-for-errors">
                {{ form_errors(form) }}
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form_row(form.site) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.keyword) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.dateDebut) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.dateFin) }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form_row(form.ManagerFilter) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.RegisterFilter) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.NotRegisterFilter) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.OutDatedFilter) }}
                    </div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-common" data-label="Enregistrer">
                            Enregistrer
                        </button>
                    </div>
                </div>
            </div>
        </div>
        {{ form_end(form) }}
        <div class="row">
            <div id="table-ville" class="col-md-12">
                <div class="loader" ></div>
                {% include 'sortie/sorties_table.html.twig' %}
            </div>
        </div>
        <div class="row">
            <div class="pagination col-md-12">
{#                {{ knp_pagination_render( allSorties) }}#}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{{ asset('libs/jquery-3.3.1/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ asset('js/sorties.js') }}"></script>
    <script src="{{ asset('js/create_sortie.js') }}"></script>
    <script
            src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
            integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
            crossorigin="anonymous"
    >
    </script>
{% endblock %}

templates/sortie/sorties_table.html.twig
<div class="table-wrapper-scroll-y my-custom-scrollbar">

    <table class="table table-bordered table-striped mb-0" id="table-sorties" data-csrf="{{ csrf_token('table_csrf_token_JFN4F4if') }}" >
        <thead>
        <tr>
            <th scope="col">Nom de la sortie</th>
            <th scope="col">Date de la sortie</th>
            <th scope="col">Clôture</th>
            <th scope="col">Inscrits/places</th>
            <th scope="col">Etat</th>
            <th scope="col">Inscrit</th>
            <th scope="col">Organisateur</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for sortie in allSorties %}
            {% set registred = 0 %}
            <tr>
                <th scope="row">
                    {{ sortie.nom }}
                </th>
                <td scope="row">
                    {{ sortie.datedebut |date("m/d/Y")}}
                </td>
                <td scope="row">
                    {{ sortie.datecloture |date("m/d/Y")}}
                </td>
                <td scope="row">
                    {{ sortie.inscriptions |length }} / {{ sortie.nbinscriptionsmax }}
                </td>

                <td scope="row">
                    {{ sortie.etat.libelle }}
                </td>
                <td scope="row">
                    {% for inscription in sortie.inscriptions %}
                        {%  if inscription in app.user.inscriptions %}
                            <i class="fas fa-fist-raised"></i>
                        {% endif %}
                    {% endfor %}
                </td>
                <td scope="row">
                    {{ sortie.organisateur.nom }}
                </td>
                <td scope="row">
                    <a href={{ path("sortie_detail", {id: sortie.id})}}><i class="fas fa-eye"></i></a>
                    {% for inscription in sortie.inscriptions %}
                        {%  if inscription in app.user.inscriptions and sortie.etat.libelle == 'Ouverte' %}
                            {% set registred = 1 %}
                            <a class="unregister" href="" data-id={{ sortie.id }}><i class="fas fa-ban"></i></a>
                        {% endif %}
                    {% endfor %}
                    {% if registred == 0 and sortie.etat.libelle == 'Ouverte' %}
                        <a class="register" href="" data-id={{ sortie.id }}><i class="fas fa-sign-in-alt"></i></a>
                    {% endif %}
                    {% if sortie.organisateur.id == app.user.id and sortie.etat.libelle == 'Ouverte' %}
                        <a class="cancel" href="" data-id={{ sortie.id }}><i class="fas fa-trash-alt"></i></a>
                    {% endif %}
                    {% if sortie.organisateur.id == app.user.id and sortie.etat.libelle == 'Créée' %}
                        <a class="edit" href={{ path("sortie_edit", {id: sortie.id})}}><i class="fas fa-edit"></i></a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

</div>